name: UI
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  run_tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
  
      - name: Set up Java
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Build
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Test
        run: mvn test
      - name: Archive report and screenshot
        uses: actions/upload-artifact@v2
        with:
          name: AutoTest
          path: |
            vitrinalive_selenium-ui-test\cucumber_results
            vitrinalive_selenium-ui-test\failed_scenarios